# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEkOk_cpp <- function(Sk, ng, G) {
    .Call(`_FHclust_getEkOk_cpp`, Sk, ng, G)
}

getA_cpp <- function(Ok, lam, G, d) {
    .Call(`_FHclust_getA_cpp`, Ok, lam, G, d)
}

sumSk_wt_cpp <- function(Sk, wt, d, G) {
    .Call(`_FHclust_sumSk_wt_cpp`, Sk, wt, d, G)
}

newD3_MM_cpp <- function(D, d, G, Wk, Ak, tmax = 100L) {
    .Call(`_FHclust_newD3_MM_cpp`, D, d, G, Wk, Ak, tmax)
}

newD4_MM_cpp <- function(D, d, G, Wk, Ak, tmax = 100L) {
    .Call(`_FHclust_newD4_MM_cpp`, D, d, G, Wk, Ak, tmax)
}

newD_cpp <- function(D, d, G, Wk, Ak, tmax = 100L) {
    .Call(`_FHclust_newD_cpp`, D, d, G, Wk, Ak, tmax)
}

testval_cpp <- function(Wk, Ak, D, G) {
    .Call(`_FHclust_testval_cpp`, Wk, Ak, D, G)
}

msEEE_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msEEE_cpp`, Sk, ng)
}

msEEV_cpp <- function(Sk, ng, eplison = 1e-12, max_iter = 100L) {
    .Call(`_FHclust_msEEV_cpp`, Sk, ng, eplison, max_iter)
}

msVEV_cpp <- function(Sk, ng, eplison = 1e-14, max_iter = 100L) {
    .Call(`_FHclust_msVEV_cpp`, Sk, ng, eplison, max_iter)
}

msVVV_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msVVV_cpp`, Sk, ng)
}

msEEI_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msEEI_cpp`, Sk, ng)
}

msVEI_cpp <- function(Sk, ng, eplison = 1e-20, max_iter = 100L) {
    .Call(`_FHclust_msVEI_cpp`, Sk, ng, eplison, max_iter)
}

msEVI_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msEVI_cpp`, Sk, ng)
}

msVVI_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msVVI_cpp`, Sk, ng)
}

msEII_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msEII_cpp`, Sk, ng)
}

msVII_cpp <- function(Sk, ng) {
    .Call(`_FHclust_msVII_cpp`, Sk, ng)
}

msVVE_cpp <- function(Sk, ng, eplison = 1e-20, max_iter = 10L) {
    .Call(`_FHclust_msVVE_cpp`, Sk, ng, eplison, max_iter)
}

msEVE_cpp <- function(Sk, ng, eplison = 1e-20, max_iter = 10L) {
    .Call(`_FHclust_msEVE_cpp`, Sk, ng, eplison, max_iter)
}

msVEE_cpp <- function(Sk, ng, eplison = 1e-14, max_iter = 100L) {
    .Call(`_FHclust_msVEE_cpp`, Sk, ng, eplison, max_iter)
}

msEVV_cpp <- function(Sk, ng, eplison = 1e-12, max_iter = 100L) {
    .Call(`_FHclust_msEVV_cpp`, Sk, ng, eplison, max_iter)
}

model_type_cpp <- function(modelname, Sk, ng, mtol = 1e-18, mmax = 10L) {
    .Call(`_FHclust_model_type_cpp`, modelname, Sk, ng, mtol, mmax)
}

compose_clusters_fast <- function(nF, nH, mu, sigma, sigma_inv, psi, alpha) {
    invisible(.Call(`_FHclust_compose_clusters_fast`, nF, nH, mu, sigma, sigma_inv, psi, alpha))
}

draw_multiple <- function(probs) {
    .Call(`_FHclust_draw_multiple`, probs)
}

maximization_step_1_fast <- function(nF, nH, mu, sigma, sigma_inv, psi, alpha, pi, zhat, data, psi_type, cov_type) {
    invisible(.Call(`_FHclust_maximization_step_1_fast`, nF, nH, mu, sigma, sigma_inv, psi, alpha, pi, zhat, data, psi_type, cov_type))
}

maximization_step_2_fast <- function(nF, nH, mu, sigma, sigma_inv, psi, alpha, pi, zhat, data, Amat, bvec) {
    invisible(.Call(`_FHclust_maximization_step_2_fast`, nF, nH, mu, sigma, sigma_inv, psi, alpha, pi, zhat, data, Amat, bvec))
}

log_phi <- function(x, mu, sigma) {
    .Call(`_FHclust_log_phi`, x, mu, sigma)
}

log_phi_inv <- function(x, mu, sigma_inv) {
    .Call(`_FHclust_log_phi_inv`, x, mu, sigma_inv)
}

expectation_step_fast <- function(nF, nH, mu, sigma, sigma_inv, pi, zhat, data, hold_z, stochastic, loglik) {
    invisible(.Call(`_FHclust_expectation_step_fast`, nF, nH, mu, sigma, sigma_inv, pi, zhat, data, hold_z, stochastic, loglik))
}

cpp_iteration_fast_progress <- function(state, times, verbosity, show_progress, AECM_epsilon = 1e-2) {
    .Call(`_FHclust_cpp_iteration_fast_progress`, state, times, verbosity, show_progress, AECM_epsilon)
}

